#!/usr/bin/env bash
# Tranfer a file from a client to another

if [ $# -lt 4 ]
then
	echo "Usage: 0-tranfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
