#!/usr/bin/env bash
# install Nginx with init file with the message "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > sudo /var/www/html/index.nginx-debian.html
sudo service nginx start
