#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
# The script displays:
# - username
# - user id
# - Home directory path for the user

while read -r line
do
	cut -d : -f 1,3,6 <<< "$line"
done < "/etc/passwd"
