#!/usr/bin/env bash
# This script loops from 1 to 10 and:
# - displays `bad luck` for the 4th loop iteration
# - displays `good luck` for the 8th loop iteration
# - displays `Best School` for the other iterations

n=1
while [[ $n -le 10 ]] 
do
	if [[ $n -eq 4 ]]
	then
		echo "bad luck"
	elif [[ $n -eq 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	n=$((n + 1))
done
