#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 mintes:
# - display hours from 0 to 12
# - display minutes from 1 to 59

hour=0
minute=0

while [[ $hour -le 12 ]]
do
	echo "Hour: $hour"
	minute=1
	while [[ $minute -le 59 ]]
	do
		echo $minute
		minute=$((minute + 1))
	done
	hour=$((hour + 1))
done
