#!/usr/bin/env bash
# This script displays:
# - The content of the current directory
# - In a list format
# - Where only the part of the name after the first dash is displayed

for name in *
do
	echo "${name//[^-]*-/}"
done
